device_test: tinker_assembler latch.cpp device.cpp adder.cpp add4.cpp divider.cpp comparator.cpp two_complement.cpp multiplier.cpp logic.cpp shifter.cpp multiplexer.cpp demultiplexer.cpp register_file.cpp mp_register_file.cpp control_array.cpp device_test.cpp instruction_fetch.cpp instruction_decode.cpp
	$(CXX) $(CFLAGS) -o device_test latch.cpp device.cpp adder.cpp add4.cpp divider.cpp comparator.cpp two_complement.cpp multiplier.cpp logic.cpp shifter.cpp multiplexer.cpp demultiplexer.cpp register_file.cpp mp_register_file.cpp control_array.cpp device_test.cpp instruction_fetch.cpp instruction_decode.cpp

tinker_assembler: tinker_assembler.cpp
	$(CXX) $(CFLAGS) -o tinker_assembler tinker_assembler.cpp